spring:
  application:
    name: YumDash

  datasource:
    url: jdbc:postgresql://localhost:5432/yum-dash
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

file:
  upload-dir: D:\\YumDashImages

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
